### ISSUE TITLE
ValueError("New shape is shitty")

### ISSUE THREAD

**Issue by zeeem** [tjvandal/deepsd#3]
Not running in python 3.7 so I used python 2.7 instead.
This is the error I am getting. (changed years to 2017 & 2018 in the config.ini)

ERROR: 

> 2018-12-31 00:00:00
> ('making temp dir', '/tmp/tmppHxmZ0')
> Year: 2017
> ('data dir', u'data/prism/ppt/raw')
> ('highres file', u'data/prism/ppt/raw/prism_ppt_4km2_2017.nc')
> ('Making patches or year:', 2017)
> scratch/ppt_004_008/train_2017.tfrecords
> trying to make patches
> tcmalloc: large alloc 2541805568 bytes == 0x55940c214000 @  0x7f74314b81e7 0x7f74160b1771 0x7f741611628e 0x7f7416116847 0x7f74161b0810 0x5592ca1816da 0x5592ca17ed3a 0x5592ca18683e 0x5592ca186452 0x5592ca17ed3a 0x5592ca18683e 0x5592ca17ed3a 0x5592ca18683e 0x5592ca17ed3a 0x5592ca18683e 0x5592ca17ed3a 0x5592ca17e7b9 0x5592ca1af4df 0x5592ca1aa2d2 0x5592ca1a974d 0x5592ca158de4 0x7f74310b5b97 0x5592ca15869a
> Traceback (most recent call last):
>   File "prism.py", line 364, in <module>
>     main_prism_tf(config)
>   File "prism.py", line 334, in main_prism_tf
>     d.make_patches(tf_file, size=patch_size, stride=20, scale1=scale1, scale2=scale2)
>   File "prism.py", line 230, in make_patches
>     mask, da1, da2, elev = self.resolve_data(scale1, scale2)
>   File "prism.py", line 213, in resolve_data
>     Y_interp = utils.interp_da(Y, scale1)
>   File "/gdrive/My Drive/Colab Notebooks/deepsd/utils.py", line 53, in interp_da
>     raise ValueError("New shape is shitty")
> ValueError: New shape is shitty

**Comment by zeeem** [comment]
daily/ppt/2018/PRISM_ppt_stable_4kmD2_20181231_bil.zip
2018-12-31 00:00:00
('making temp dir', '/tmp/tmppHxmZ0')
Year: 2017
('data dir', u'data/prism/ppt/raw')
('highres file', u'data/prism/ppt/raw/prism_ppt_4km2_2017.nc')
('Making patches or year:', 2017)
scratch/ppt_004_008/train_2017.tfrecords
trying to make patches
tcmalloc: large alloc 2541805568 bytes == 0x55940c214000 @  0x7f74314b81e7 0x7f74160b1771 0x7f741611628e 0x7f7416116847 0x7f74161b0810 0x5592ca1816da 0x5592ca17ed3a 0x5592ca18683e 0x5592ca186452 0x5592ca17ed3a 0x5592ca18683e 0x5592ca17ed3a 0x5592ca18683e 0x5592ca17ed3a 0x5592ca18683e 0x5592ca17ed3a 0x5592ca17e7b9 0x5592ca1af4df 0x5592ca1aa2d2 0x5592ca1a974d 0x5592ca158de4 0x7f74310b5b97 0x5592ca15869a
Traceback (most recent call last):
  File "prism.py", line 364, in <module>
    main_prism_tf(config)
  File "prism.py", line 334, in main_prism_tf
    d.make_patches(tf_file, size=patch_size, stride=20, scale1=scale1, scale2=scale2)
  File "prism.py", line 230, in make_patches
    mask, da1, da2, elev = self.resolve_data(scale1, scale2)
  File "prism.py", line 213, in resolve_data
    Y_interp = utils.interp_da(Y, scale1)
  File "/gdrive/My Drive/Colab Notebooks/deepsd/utils.py", line 53, in interp_da
    raise ValueError("New shape is shitty")
ValueError: New shape is shitty

**Comment by sanket-p** [comment]
@zeeem thanx for raising this , I am also facing the same issue

**Comment by zeeem** [comment]
@tjvandal , I hope you can help us.

**Comment by tjvandal** [comment]
Hi @zeem @sanket-p , I'm looking into it, haven't touched this code in a while but that ValueError I added in there is fairly amusing. Did daily/ppt/2018/PRISM_ppt_stable_4kmD2_20181231_bil.zip download completely?  I suspect the binary is too short and cannot be reshaped.

**Comment by zeeem** [comment]
Hello @tjvandal  , Yes it downloaded completely.  I tried changing the years to 2016, 2017 and 2018 everytime after downloading and it raises this error.


('Making patches or year:', 2017)
scratch/ppt_004_008/train_2017.tfrecords
trying to make patches
tcmalloc: large alloc 2541805568 bytes == 0x55940c214000 @  0x7f74314b81e7 0x7f74160b1771 0x7f741611628e 0x7f7416116847 0x7f74161b0810 0x5592ca1816da 0x5592ca17ed3a 0x5592ca18683e 0x5592ca186452 0x5592ca17ed3a 0x5592ca18683e 0x5592ca17ed3a 0x5592ca18683e 0x5592ca17ed3a 0x5592ca18683e 0x5592ca17ed3a 0x5592ca17e7b9 0x5592ca1af4df 0x5592ca1aa2d2 0x5592ca1a974d 0x5592ca158de4 0x7f74310b5b97 0x5592ca15869a
Traceback (most recent call last):

**Comment by tjvandal** [comment]
I reproduced that error and committed a fix.
https://github.com/tjvandal/deepsd/commit/0d29487064d7513fb521e928b372fa3b1e9b8147

**Comment by zeeem** [comment]
@tjvandal thanks a lot.. let me try running the code, will let you know if that works. thanks again.

@sanket-p hope you will find the fix useful as well.

**Comment by sanket-p** [comment]
Thank you for your help @tjvandal In my case I am not sure about the data as I had few errors related to packages as  I was switching from python 3 to 2. Though, your recent update will do. I will be running this right away. Also, thank you for assistance @zeeem

**Comment by sanket-p** [comment]
Yepppp... the codes are working and I got those patches ready.

**Comment by zeeem** [comment]
@tjvandal , the first step worked fine.

but at the 2nd step when I am trying the "bash run_job.sh", it's showing this error.

> Traceback (most recent call last):
>   File "train.py", line 25, in <module>
>     FLAGS._parse_flags()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/flags.py", line 85, in __getattr__
>     return wrapped.__getattr__(name)
>   File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 473, in __getattr__
>     raise AttributeError(name)
> AttributeError: _parse_flags
> Traceback (most recent call last):
>   File "train.py", line 25, in <module>
>     FLAGS._parse_flags()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/flags.py", line 85, in __getattr__
>     return wrapped.__getattr__(name)
>   File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 473, in __getattr__
>     raise AttributeError(name)
> AttributeError: _parse_flags

Although I am still trying to figure the solution to this, I would highly appreciate it if you could look into the issue.

**Besides, Upon going through all the codes, I understood that we will be getting the res.pdf as the final result after running the inference.py. So I was wondering how can I get the result like below example:
![image](https://user-images.githubusercontent.com/16939985/68782751-1aa05e80-05f7-11ea-91ba-a504c9c8c67a.png)

Also, I was wondering how you prepared the elevation for this project. really appreciate your assistance.**
Thanks

**Comment by tjvandal** [comment]
The codes available will not generate that figure. Use Tensorflow version 1.5 for FLAGS to parse. That object is deprecated in recent versions.

**Comment by zeeem** [comment]
@tjvandal , sorry to bother again. But I tried tensorflow 1.5, 1.15 and also 1.14 but i am getting the same error:

> Traceback (most recent call last):
>   File "train.py", line 25, in <module>
>     FLAGS._parse_flags()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
>     return wrapped.__getattr__(name)
>   File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 473, in __getattr__
>     raise AttributeError(name)
> AttributeError: _parse_flags
> Traceback (most recent call last):
>   File "train.py", line 25, in <module>
>     FLAGS._parse_flags()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
>     return wrapped.__getattr__(name)
>   File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 473, in __getattr__
>     raise AttributeError(name)
> AttributeError: _parse_flags

**Comment by zeeem** [comment]
also is there any other git repo where I can produce the image results like the paper? thanks in advance.
