### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by sanket-p** [tjvandal/deepsd#4]
Hey guys.. I am having this issue and the error is caused due to something with freeze_graphs
can somebody tell me the solution to this please...

@zeeem have you tried running inference.py? does that work for you? plz let me know

dropping a snip image of the error shown
![graph_attribute_error](https://user-images.githubusercontent.com/54616309/68755302-4b4fba80-062e-11ea-9003-c9ed9faebb80.PNG)

**Comment by zeeem** [comment]
@sanket-p I am facing this problem at the 2nd step.

![image](https://user-images.githubusercontent.com/16939985/68782264-5555c700-05f6-11ea-8dc2-900a26218f5b.png)

**Comment by tjvandal** [comment]
@zeeem  See the environment.yml file in this repository. FLAGS are not available on more recent versions of Tensorflow.  Use Tensorflow version 1.5 or older.

**Comment by tjvandal** [comment]
@sanket-p The model path doesn't exist.  Is this model trained?

**Comment by sanket-p** [comment]
@tjvandal yes, the model is trained and I can see the checkpoint files in scratch directory in folder named 'srcnn_ppt-008-016_64-32-1_9-3-5'

@zeeem you can replace line 25 in train.py which is "FLAGS._parse_flags()" with  "FLAGS(sys.argv)" this, and "import sys" in the beginning.

**Comment by sanket-p** [comment]
> @tjvandal yes, the model is trained and I can see the checkpoint files in scratch directory in folder named 'srcnn_ppt-008-016_64-32-1_9-3-5'
> 
I had directly executed train.py file, didnt used your run.sh file.

**Comment by sanket-p** [comment]
> > @tjvandal yes, the model is trained and I can see the checkpoint files in scratch directory in folder named 'srcnn_ppt-008-016_64-32-1_9-3-5'
> 
> I had directly executed train.py file, didnt used your run.sh file.
Yes.. this was the issue. As I executed train.py separately and it only had training of model 1, I had to separately train for model 2 which solved this issue for me.

Thank you for your time and help @tjvandal 
You are a lifesaver for me

**Comment by zeeem** [comment]
@sanket-p thanks for the suggestion but it is not working for some reason. :/
